### PR TITLE
Ported solution and source code to Visual Studio 2015 (Bug 11378)

### PR DESCRIPTION
**Pull request by keithjjones**
Fixed bug 11378

https://bugzilla.clamav.net/show_bug.cgi?id=11378

Broken: Setup projects

Invalidates pull requests #40 #41 #42

### CODE REVIEW

**Comment by vrtadmin** [comment]
This has been fixed in our internal GIT

**Comment by keithjjones** [comment]
Is that internal Git pushed here?

**Comment by vrtadmin** [comment]
We generally sync the GIT on releases and builds.

**Comment by vrtadmin** [comment]
But I believe this has been synced in the 0.99.3 branch.

**Pull request closed without merging**
